"""initial_migration

Revision ID: d42841752e3d
Revises: df69b07266fc
Create Date: 2026-05-10 20:09:12.447362

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "d42841752e3d"
down_revision: Union[str, Sequence[str], None] = "df69b07266fc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
